### ISSUE TITLE
inconsistent redefinition complaint, despite 'del'

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#110]
*Original report by [warner](https://launchpad.net/~warner) (@warner?) on [Launchpad](https://bugs.launchpad.net/bugs/1461208):*

------------------------------------

With the new pyflakes-0.9.0, and python-2.7.10, the following program:

```python
if 1:
    name = 1   # line 2
    del name
    [ name for name in [] ]  # line 4

other = 1  # line 6
del other
[ other for other in [] ]  # line 8
```

reports:

 /tmp/pf.py:4: list comprehension redefines 'name' from line 2

I see two problems:

* the 'del name' on line 3 should probably prevent the warning. (this sample
  is a stripped-down version of a larger file, in which I added the 'del
  name' to hush an earlier pyflakes complaint)

* the same pattern on lines 6+8 was not reported, the only difference being
  that it occurred at the top-level scope and not in a function scope.

thanks!
 -Brian

**Comment by Sei-Lisa** [comment]
I've just run into a minor variation of the same pattern as in the OP:

```python
if True:
   foo = 1
   foo
   del foo
[foo for foo in ()]
```

> Ah, yeah. So there was another change, which I can't find now, which addressed this situation (going from memory here):
>
>     foo = "foo"
>     if False:
>       del foo
>     print foo
>
> This would complain about the final 'print foo' referencing an undefined foo, but as you can see, this code runs just fine.

If that was ever fixed, I think that fix should be reverted. No one should expect PyFlakes to be able to determine the truth value of an expression, and the warning must be present. Consider this:

```python
import random
foo = "foo"
if random.randint(0, 9) == 0:
  del foo
print foo
```

The above will fail one every 10 times. PyFlakes can't know which, and must warn, because that's a bug. An argument could be made about handling the special case of `if False:` and `if True:` and only taking the appropriate branch ignoring the other, but that's optional and it would not be a big deal if it didn't happen.

**Comment by asottile** [comment]
closing given pyflakes no longer supports python 2
