### ISSUE TITLE
Missing import warnings when importing fully-qualified modules

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#137]
*Original report by [gward](https://launchpad.net/~gward) (@gward?) on [Launchpad](https://bugs.launchpad.net/bugs/1421013):*

------------------------------------

Importing modules using fully-qualified paths appears to confuse pyflakes. Example 1:

```
$ cat pyflakes-missed-unused-import.py
import somepackage.mod1
import somepackage.mod2

def do_something():
    somepackage.mod1.do_something()

$ pyflakes pyflakes-missed-unused-import.py
```

Expected output: an "unused import" warning about somepackage.mod2.

Actual output: no errors or warnings.

Example 2:

```
$ cat pyflakes-missed-missing-import.py
import somepackage.mod2

def do_something():
    somepackage.mod1.do_something()

$ pyflakes pyflakes-missed-missing-import.py
```

Expected output: a "missing import" error about somepackage.mod1 *and* an "unused import" warning about somepackage.mod2.

Actual output: no errors or warnings.

**Comment by asottile** [comment]
I don't think this is possible to fix statically -- here's a [write up](https://github.com/asottile/scratch/wiki/Why-doesn't-flake8-mark-this-as-an-unused-import%3F) on this I wrote a long time ago (copied below for completeness)

> Consider the following case:
> 
> ```python
> import a
> import a.b  # technically unused!
> 
> print(a.x)
> ```
> 
> `pyflakes` (the library that flake8 uses for some of the linting detection) is very timid about doing import analysis.  When considering imports, `import a` and `import a.b.c.d` *only* introduce the `a` symbol into the global scope.  Since `a` is used on line 4, both of those imports are considered "used".
> 
> One may think, this is absurd!  Surely it could know that the second import is unnecessary because of the first!
> 
> Consider this case:
> 
> ```python
> import a
> import a.b
> 
> print(a.z.x)
> ```
> 
> ```python
> # a/b.py
> import a.z
> ```
> 
> Admittedly this is a bit of an *evil* case (and you should **never** _**ever**_ do this!).  In this case, though it is equivalent to the first case, the second import _is_ necessary (to perform a side-effect of making the `a.z` module available).

**Comment by benjaminjkraft** [comment]
I would argue the second example you give should be a lint error, even though it's valid Python.  (Just as with an unused import -- and there is less harm and a more real use case for those!)  It's easy to do accidentally, but very fragile and I'm not sure I've ever seen a good reason to do it intentionally.  (We have a custom linter to check for this, in fact, and it's worked great.)

**Comment by asottile** [comment]
pyflakes isn't the place for those sorts of lints -- it has to be _definitely wrong_ not _probably wrong_ -- pylint is probably a better place for that (and I believe already implemented (?))

**Comment by benjaminjkraft** [comment]
That's a good rule, but it leaves some ambiguity as to the meaning of the word "wrong": does "wrong" here mean "crashes" or "doesn't mean what the programmer intended"?  Many existing pyflakes rules only pass the intent standard, and this one is about as definitive as it gets in that respect.

For example, this code is valid Python, and in fact has legitimate uses (if importing `foo` has side-effects):
```py
import foo
import bar

bar.baz()
```
Pyflakes, of course, reports `'foo' imported but unused`, because while legal this is in most cases not what the programmer intended.

I argue that
```py
import a.b

a.z.foo()
```
is similarly wrong: it's legal Python, and may even return the correct result, but it's almost certainly not what the programmer intended; and unlike an unused import it's difficult to come up with a case where it's intentional.

**Comment by asottile** [comment]
If you're looking for cases where it's intentional (but reported due to the flip/flop of the imports used), check out #159

I think the rule of thumb I've seen is "almost always a crash / almost always unnecessary / etc."  -- pyflakes does not have any sort of exclusion framework so it must be extremely high signal to noise ratio

**Comment by asottile** [comment]
given the comment here I'm going to close this: https://github.com/PyCQA/pyflakes/issues/137#issuecomment-519637970
