### ISSUE TITLE
Detect unused function parameters

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#147]
*Original report by [jendrikseipp](https://launchpad.net/~jendrikseipp) on [Launchpad](https://bugs.launchpad.net/bugs/949563):*

------------------------------------

Currently pyflakes 0.5 does not detect unused function arguments.

To reproduce:

$ echo "def foo(bar): pass" | pyflakes

This should warn that bar is never used, but it doesn't.

**Comment by taion** [comment]
Sorry to resurrect this old issue, but I think this is valid.

While it is indeed the case that functions may take arguments they don't use, it's often actually an error or oversight.

As such, it would be useful to have the ability to lint for these sorts of issues. I'd rather be warned of this sort of issue, and explicitly silence warnings for those, than to not have this option at all.

**Comment by myint** [comment]
@taion I think that goes against the main [design principle](https://github.com/PyCQA/pyflakes#design-principles) of Pyflakes.

Pylint might be an option for your use case.

**Comment by taion** [comment]
It's sort of tough. I think in some ways it's analogous to the "unused imports" check – sometimes they're intentional because I'm re-exporting for a specific module, but usually they're just a mistake, and ultimately (with Flake8, which I understand is downstream of here) doing a `# noqa: F401` for those few unused imports that I explicitly want is pretty good.

It's weird. I understand what you're saying, and it makes sense, but this is the sort of check that e.g. both ESLint and RuboCop have in their recommended/default ruleset ([ESLint: no-unused-vars](https://eslint.org/docs/rules/no-unused-vars), [RuboCop: Lint/UnusedMethodArgument](http://rubocop.readthedocs.io/en/latest/cops_lint/#lintunusedmethodargument)).

In practice Pyflakes via Flake8 seems to be the de facto linting tool that everyone uses, so it's odd that Pyflakes doesn't flag something that most linters elsewhere flag, and that is usually an error, just because it's sometimes not so.

**Comment by bitglue** [comment]
One common case for unused function parameters is event handlers which pass context about the event. Often handlers just care that the event happened, and ignore the parameters.

Pyflakes detects unused imports because:

1) It was the first thing it ever did.
2) Unused imports have *per se* undesirable side-effects, possibly making imports slower, introducing cycles into the module graph, etc.
3) By far the most common use case for unused imports is importing them into `__init__` or similar to re-expose the names. In this case listing the names in `__all__` is considered good practice and is sufficient to declare the import used and suppress errors from pyflakes.

An unused parameter isn't *per se* a problem of any kind, and there's no best practice which would explicitly declare a parameter as intentionally unused.

**Comment by taion** [comment]
I understand what you're saying, and given that I'm going to open this against flake8-bugbear, which seems like a better place for that rule to live.

I will say, though, that this is an example of where DX around Python tooling lags behind that in other ecosystems. Both Pylint and Flake8 take a lot more configuration to reach something like the pragmatic compromise solutions that usually catch bugs with the de facto linting tools in other ecosystems.
