### ISSUE TITLE
False positive undefined name after del in branch

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#175]
*Original report by [dimaqq](https://launchpad.net/~dimaqq) (@dimaqq?) on [Launchpad](https://bugs.launchpad.net/bugs/1308508):*

------------------------------------

Consider this test code:

```python
def foo():
    bar = 1
    if 0:
        del bar
    else:
        del bar
```

pyflakes reports test.py:6: undefined name 'bar', that is 2nd `del bar` is considered in error.

understandably it is impossible to analyse all code paths in general case, so how about tagging `bar` as `uncertain if label is present` and allowing to `del` it?

**Comment by myint** [comment]
@adhikasp found a good example of this in [`datetime`](https://github.com/python/cpython/blob/81f67b6f48820beed6e138077fd785020bbfd5d6/Lib/datetime.py#L2262).

**Comment by bitglue** [comment]
The underlying issue is conditional branches are "invisible" to pyflakes. So

```python
def foo():
    bar = 1
    if 0:
        del bar
    else:
        del bar
```

looks like:

```
def foo():
    bar = 1
    del bar
    del bar
```

Once you understand what's going on under the hood, it's often possible to rewrite the code in a way to avoid the issue, though the specific solution depends on the specific situation.

This has been a long-standing bug since it's a complex problem to track all the possible paths though the code and calculate all the possible states of the variable assignments.

**Comment by asottile** [comment]
collecting duplicates for "pyflakes doesn't do branch analysis" here: #715
