### ISSUE TITLE
Ignore "_" vars in "Unused Variable" check

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#202]
*Original report by [archardlias](https://launchpad.net/~archardlias) on [Launchpad](https://bugs.launchpad.net/bugs/1328169):*

------------------------------------

Would it be possible to ignore variables named "_" from "Unused Variable" checks?

I'm not really sure whether "_" is officially specified anywhere. But I do see it a lot and in a lot of languages including python to denote a variable to be ignored (place holder dummy). PyLint implements this pseudo(?)-convention (? second-hand knowledge).

Would be great, since I would love to be explicit about "things returned but not used" instead of just calling without assignment which looks tantamount to "this function does never return anything / does not contain a return statement". A great plus in signature visibility throughout the code, specially for first-time readers.

Best regards,
~arlias

**Comment by NeilGirdhar** [comment]
Any progress on this?

**Comment by earonesty** [comment]
It is absolutely a common convention:

Terse example taken from: https://stackoverflow.com/questions/431866/ignore-python-multiple-return-value

```
def f():
    return 1, 2, 3
_, _, x = f()
```

**Comment by bitglue** [comment]
@earonesty yes, and that code does not raise any error in pyflakes.

**Comment by bitglue** [comment]
To summarize the discussion so far: common cases such as unpacking:

```
def f():
    return 1, 2, 3

def g():
    _, _, x = f()
    return x
```

or iteration:

```
def boink_10_times():
    for _ in range(10):
        print("boink")
```

already _do not raise errors_. The only error case seems to be deliberately assigning _just_ to `_`, such as:

```
def foo():
    _ = 42
<stdin>:2: local variable '_' is assigned to but never used
```

This doesn't seem to be a common idiom. A `for` loop _must_ have a variable. Unpacking _must_ assign each component to some name. But in this case, the choice to assign to `_` was optional and deliberate. Why wouldn't pyflakes complain about this?

The reasons for assigning to `_` mentioned so far are:

- Assigning unused function parameters to `_` to silence pylint. Satisfying pylint is not an objective for pyflakes (in fact the entire project was borne of frustration with pylint's propensity for such superfluous errors).
- Assigning the result of a function which does not return None to `_` to "be explicit" about ignoring the return value.

Are other cases? Is there evidence that this "assigning to `_` to show a return value is ignored" pattern is common?

**Comment by asmeurer** [comment]
Assigning to `_` might be valuable in doctest mode, as a way to silence the output.

**Comment by nerdvegas** [comment]
Assigning to '_' is pretty common (I say that with ~20 years dev time). This tells anyone reading the code that you are calling a function that normally returns something useful that people want, but that, in this particular (and typically unusual) edge case, you are discarding the result. This is a way to highlight an unusual use case, and that is never a bad thing.

This debate about whether assigning to '_' is correct or not misses the point - this _is_ a convention which _does_ exist, so imo it should be supported.

I've just hit this myself, and have disappointingly had to `#  noqa` it out.

**Comment by krader1961** [comment]
Sadly, I can only +1 @nerdvegas comment rather than the +100 it deserves. Assigning to `_` at the top of a function/method is an invaluable way to silence lint warnings about unused parameters while communicating to the human reader that the author intentionally meant to not use the parameter. It is an extremely useful convention. The alternative is a magic comment to silence the linter about the unused parameter. But I fail to see how that is any different from assigning to `_`.

**Comment by bitglue** [comment]
Can anyone support the assertion that this is a common pattern with a reference to some code? A reference to a mature, popular body of code where this is consistently a pattern may be enough to justify the change.

I'd like to keep the comments focused on data. If you'd like to agree with something that's already been said, a thumbs-up reaction is sufficient. I'll take those numbers into account.

**Comment by fvisin** [comment]
It's not an easy search, as most engines will ignore or not accept '_' as a search string.
I found this by manual inspection:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/normalization_test.py

there are ~40 references just in this file and the project has ~100K stars on Github. I am sure many more similar examples can be found.

**Comment by krader1961** [comment]
I'm an ex-Google software engineer. Within Google the `_ = unused_param` pattern is universal in their Python code. You'll find it enshrined in the [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html) in the "Lint" section of the document. So any current or former Google SWE is likely to have propagated this idiom to other projects. It wouldn't surprise me if other companies and projects have adopted this as a standard idiom independent of Google.

**Comment by sigmavirus24** [comment]
Thanks for that data-point @krader1961. I think we're all agreed now that this would be worthwhile to implement and just need someone to implement it :)

**Comment by smontanaro** [comment]
I continue to be surprised that pyflakes doesn't yet recognize variables with at least leading underscores (if not just a lone underscore) as taken to mean, "Yes, I know this variable is unused. I know what I'm doing, so stop bothering me about this."

Here's a PR:

https://github.com/PyCQA/pyflakes/pull/334

**Comment by joaoe** [comment]
I sometimes use the pattern:
```
try:
  _ = some_object.property
except AttributeError:
  some_object.property = some_expensive_operation()
```
so, the way I avoid `pyflakes` complaining is to write it as `(_,) = ...`. But it does look weird.

**Comment by asmeurer** [comment]
I know this is already implemented, but I just wanted to point out a use-case for redefining `_` that never occurred to me to point out here. Often when you have a decorator that adds a function to a registry, the name of the function is irrelevant so `_` is used. See for instance the [singledispatch](https://docs.python.org/3/library/functools.html#functools.singledispatch) decorator from the standard library (in this case, the only other natural name other than `_` is the name of the function itself, which pyflakes would warn about).  I actually saw this a lot with prompt-toolkit's keybindings ([example](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/bindings/emacs.py)), but is never occurred to me to point it out here. Of course, function and class definitions are special because, like loops, they require a name, but applying the rule to all names seems like a good idea if just for consistency.

**Comment by earonesty** [comment]
Ignoring the return value of a function that doesn't return "void" is considered bad form.   In python, the same rule should apply. _unneeded_group_id = func()   is far more clear than func().   Why?   Because it expresses that a) the return value is a "group id" and it's "not needed".   Whereas func() expresses that the func() may return None - we have no idea.
