### ISSUE TITLE
Detect type hint comments: PEP484

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#247]
*Original report by [w-thomas-q](https://launchpad.net/~w-thomas-q) on [Launchpad](https://bugs.launchpad.net/bugs/1587170):*

------------------------------------

Hi,

thanks for this really great tool!
One issues I stumbled upon was that type hints seem to be ignored / not detected.
For example, we have an import at the top of a file:

    from typing import List

And then later in an `__init__` function something like this:

    self.scripts = []  # type: List[script.Script]

Now running pyflakes (through flake8) gives me this error:

    foo.py:4:1: F401 'List' imported but unused

PEP484 defines this kind of type comments.
Is there an option to enable type hint detection?
Or can we have that as feature request? I guess I'm fine with type comments only for the time being, but of course a fully PEP484 compliant solution would be greatly appreciated :)

Thanks!

**Comment by wsanchez** [comment]
Note `flake8` issue on this: https://gitlab.com/pycqa/flake8/issues/342

**Comment by wsanchez** [comment]
Actually, perhaps a better flake8 issue on this: https://gitlab.com/pycqa/flake8/issues/118

**Comment by adamrothman** [comment]
pyflakes also incorrectly reports unused imports when using the variable annotation syntax defined by [PEP 526](https://www.python.org/dev/peps/pep-0526/):

```python
from typing import Dict

x: Dict[str, str] = {}
```

Running pyflakes over this results in `F401 'typing.Dict' imported but unused`.

**Comment by myint** [comment]
@adamrothman I can't seem to reproduce your error. What version of `pyflakes` are you using? Thanks.

`foo.py`:
```python
from typing import Dict

x: Dict[str, str] = {}
```

```
$ pyflakes foo.py
$ pyflakes  --version
1.6.0
```

**Comment by wsanchez** [comment]
I also can't reproduce this with the Py3.6 syntax using pyflakes 1.6.0 (and Python 3.6).

If you switch to the comment syntax, I do see the "unused import" error (as expected).

**Comment by adamrothman** [comment]
Thanks for investigating @myint @wsanchez. I'm running `pyflakes` by way of `flake8`, and it looks like `flake8` had only installed `pyflakes` 1.5.0. Upgrading to 1.6.0 has resolved my issue.

Also, though it doesn't matter now, the example I provided was simplified for illustration but it turns out that particular snippet actually doesn't reproduce the error under 1.5.0. It looks like the annotated variable has to be inside of a function in order to trigger the error. I can reliably reproduce the error (with `pyflakes` 1.5.0) using this file:

```python
# -*- coding: utf-8 -*-
from typing import Any
from typing import Dict


def do_something():
    x: Dict[str, Any] = {}
    print(x)
```

```
$ pyflakes --version        
1.5.0

$ pyflakes test.py
test.py:2: 'typing.Any' imported but unused
test.py:3: 'typing.Dict' imported but unused
```

In any case, upgrading `pyflakes` has resolved my issue. Thanks all!

**Comment by adamrothman** [comment]
Should `flake8`'s `pyflakes` dependency should be updated? It's currently `pyflakes >= 1.5.0, < 1.7.0`, but if 1.5.0 doesn't fully support PEP 526 it should probably be excluded.

**Comment by wsanchez** [comment]
Nothing prevents you from using pyflakes 1.6.0, so why would an exclusion be necessary?

**Comment by OddBloke** [comment]
pyflakes still doesn't handle type _comments_, right?

**Comment by bitglue** [comment]
Indeed you're right. I misread the ticket.

**Comment by henryJack** [comment]
Hi,

I love the tool but I am also having this issue. This one seems a little bit strange as it only errors for `Union` not `List`.

```
from typing import List, Union

my_list: List[Union[float, str]] = []
```

This gives me a console error when running Pyflakes of:

 `F401 'typing.Union' imported but unused`

--> A work around, for the time being, would be to add this to the import statement:
`from typing import List, Union # noqa, flake8 issue`

**Comment by OddBloke** [comment]
@henryJack I'm not sure that's the same issue. You're using full blown type annotations there, not comments (i.e. `my_list = []  #type: List[Union[float, str]]`).

**Comment by myint** [comment]
@henryJack What version of `pyflakes` are you using?

https://github.com/PyCQA/pyflakes/pull/88

**Comment by henryJack** [comment]
@OddBloke - Fixed the issue by upgrading pyflakes 1.6.0! Also, FYI:

python 2 type hints --> `my_list = []  # type: List[Union[float, str]]`
Python <=3.6 Type Hints -->  `my_list: List[Union[float, str]] = []`

**Comment by DuncanHills** [comment]
Can someone point me to another PR or diff that is structurally similar? I wouldn't mind taking a stab at this.

**Comment by bitglue** [comment]
@DuncanHills grepping the git log for "annotat" as in "annotated", "annotations", etc you can find a few.

**Comment by michaelwayman** [comment]
I also get `F401 'typing.Dict' imported but unused`

```py
from typing import Dict

def foo():
    bar: Dict[str, str] = {'hello': 'world'}
```
upgrading from `pyflakes==1.5.0` to `pyflakes==1.6.0` fixes the issue.

**Comment by DuncanHills** [comment]
@michaelwayman that is a type annotation, not a type hint comment.

**Comment by yobuntu** [comment]
is there any new on this issue ?

**Comment by martinarroyo** [comment]
I can still replicate:

```python
from typing import Iterable, List

def my_function(a, b):
    # type: (List[str], List[str]) -> None
    
``` 

Raises `F401 'typing.List' imported but unused`.

This is the output of `flake8 --version`:

```
3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.12 on Linux
```

**Comment by wlansu** [comment]
There is also this problem:

```
if typing.TYPE_CHECKING:
    from .constants import CONSTANT

def my_function() -> 'CONSTANT':
```

This raises a F401 error, it seems to be specifically related to Constants.

**Comment by PeterJCLaw** [comment]
@DuncanHills did you make any progress on this?

I've just started typing a good sized Python 3.5 codebase and we're hitting this case quite a bit, so I'd be interested in helping out.

@bitglue do you have any thoughts on the direction of the solution here?
I don't know much about the internals of pyflakes, though I recall reading (on what I think was a [predecessor issue](https://gitlab.com/pycqa/flake8/issues/118) to this one) that switching to using [`typed-ast`](https://pypi.org/project/typed-ast/) was a likely solution, but that was being held back by the lack of maturity of that project.

A related question I see is whether `pyflakes` should error about symbols it finds in type comments but which aren't defined. I suspect the answer is that it _shouldn't_, because it should leave that to `mypy`, but I could be convinced otherwise.

**Comment by wsanchez** [comment]
> A related question I see is whether `pyflakes` should error about symbols it finds in type comments but which aren't defined. I suspect the answer is that it _shouldn't_, because it should leave that to `mypy`, but I could be convinced otherwise.

I tend to run `flake8` more often than other checks, specifically because it is fast; my editor uses it to do this for me, in fact.  If it's not an expensive check, there's no reason to avoid reporting it just because another checker may also do so.

**Comment by PeterJCLaw** [comment]
> I tend to run `flake8` more often than other checks, specifically because it is fast; my editor uses it to do this for me, in fact. If it's not an expensive check, there's no reason to avoid reporting it just because another checker may also do so.

Indeed, this was the main reason I could see _for_ having `pyflakes` check it.

Looking at the reasons against, the ones I can see are that:
* it might slow down the checks (as already noted)
* we should leave it to a more qualified checker because it could be considered not our remit (as already noted)
* this would become another check which `pyflakes` would need to maintain (and which could get out of step with the "correct" implementation in the user's choice of type checker)
* users might assume that `pyflakes` is doing more towards type checking than it actually is

Assuming that the performance overhead is minimal, I'm not sure that any of these are particularly compelling when we consider that `flake8` (and I assume therefore `pyflakes`) already warns about other undeclared symbols.

**Comment by asottile** [comment]
I took a stab at this in #400 -- please take it for a spin since I'm fairly certain there's edge cases I'm not considering.

I took an approach which makes this easiest to plug into `flake8` which will happily pass along `tokens` for us.  When run standalone however, pyflakes needs to handle tokenizing itself.

I then cross-referenced the tokens against the ast and use that during traversal to handle type comments at the appropriate places
