### ISSUE TITLE
Incorrect 'local variable is assigned to but never used' warning with del in if block

### ISSUE THREAD

**Issue by H0R5E** [PyCQA/pyflakes#362]
## Problem Description

I've noticed that "local variable 'blah' is assigned to but never used' will be triggered on the edge case of a deleted variable inside an if statement.

I encounted the issue using Spyder and there is a (closed) companion bug at spyder-ide/spyder#7795.

### What steps reproduce the problem?

Consider the following function:

```
def test():
    
    if True:
        color = 1
        del color
```

The `color` variable on line 4 generates the error "local variable 'color' is assigned to but never used" when checked with pyflakes.

### What is the expected output? What do you see instead?

The warning should not be produced. If the `del` statement is replaced with `print` no warning is issued. Also, the warning is not issued if the `if` block is removed.

## Versions

python = 2.7.14
pyflakes = 1.6.0 & 2.0.0

**Comment by H0R5E** [comment]
This seems pretty similar to #175, but this is a slightly different invocation to the example posted there.

**Comment by bitglue** [comment]
I'm a bit puzzled as to why this only happens inside an `if` block, but regardless, the error seems right on to me. I would fix it by modifying the code to be:

```
def test():
    if True:
        1
```

which is a bit nonsensical, since `1` has no side-effect. But if we imagine it's instead a function call with a side-effect, it makes more sense.

In other words, defining a variable just to delete it serves no purpose.

Do you have a use case where it does?

**Comment by H0R5E** [comment]
I would totally agree with you, but then why does this not raise a similar warning?

```
def test():
    
    color = 1
    del color
```

You """"might"""" do this to look at the operation of the garbage collector (maybe). Ultimately is it wrong, per se? Even if it doesn't do anything useful?

**Comment by bitglue** [comment]
Things which are almost certainly useless are "errors" according to pyflakes. For example, importing a module but not using it.

If there's a legitimate use case where there are spurious errors, they tend to be suppressed. For example pyflakes will complain about an unused variable, but not if the variable was created as part of expanding a tuple, like:

    def returns_a_pair():
        return (1, 2)

    foo, bar = returns_a_pair()

The reasoning is unpacking a tuple like this is pretty common, and each part must be given a name, even if it goes unused.

If the only use case for doing something "useless" is contrived or extremely rare, the tendency is to let it be an error. For example, importing a module then not using it.

**Comment by krader1961** [comment]
> Ultimately is it wrong, per se? Even if it doesn't do anything useful?

Yes, it is wrong precisely because it doesn't do anything useful. All languages let you write things that are legally allowed by the language but pointless or likely to confuse a reader or make it easier to accidentally introduce a real bug in the future.

I've been working on trying to keep the Korn Shell project alive. It is full of dangerous idioms such as `if (c = *s++) { ... }`. Is that supposed to be an assignment and test for a non-null char or an equality test? Just because C lets you write that and gives it a well defined meaning doesn't mean it's a good idea to write it that way. One of the ways tools like `oclint` and `pyflake` help is by pointing out things that don't make sense; such as an assignment to a var which is never read.

**Comment by H0R5E** [comment]
I think there is a use case for clearing something from memory, particularly for interacting with frameworks in wrappers (like PyQt for example). I'm thinking of something like this:

```
# This may be the only way to access the object you need to clear
thing_i_need_to_remove = framework.getThing() 

# Assuming the wrapper understands what to do with del
del thing_i_need_to_remove
```

**Comment by bitglue** [comment]
I guess you are `del thing_i_need_to_remove` ends up calling `thing_i_need_to_remove.__del__()`, so this code triggers some cleanup?

I don't believe that's the case: `del` only undefines the variable, same as if it was never assigned in the first place, or if it's just left to go out of scope normally for example when the function returns.

**Comment by sigmavirus24** [comment]
> I don't believe that's the case: del only undefines the variable, same as if it was never assigned in the first place, or if it's just left to go out of scope normally for example when the function returns.

Exactly this. `__del__` is only called when the refcount hits 0 if I remember correct. So if your framework still references it, your `del` does not trigger the magic method. `__del__` is problematic for this very reason because clean-up may not happen until the end and some things, e.g., modules may be undefined by that point.

**Comment by H0R5E** [comment]
Yeah, I totally understand your very valid points.

Is "_assigned to but never used_" the correct warning to be generating for this though? I'm afraid I don't know all the possible messages, so I'm not sure if there is a more appropriate one available?

**Comment by sigmavirus24** [comment]
Well you're not using it. You're deleting the reference before it could be used.

**Comment by krader1961** [comment]
I feel compelled to point out that `del var_name` is almost never needed. In the 15+ years I've been programming in Python I can can't on one hand the number of times using `del` to unbind a name from an object was appropriate and necessary. And I say that as someone who has used advanced features such as writing a metaclass and implementing a type-safe version of `namedtuple`. The O.P.'s original example is a good example for why this warning exists.

**Comment by H0R5E** [comment]
I've used del to deallocate memory from large arrays as part of a long algorithm for solving the interaction of wave energy conveters. So in my experience del is definitely useful in some cases, but this was always after the data had been consumed in some way.

Shall I close this and start a new bug for the case where the warning is not given?
