### ISSUE TITLE
pyflakes >2.0.0 throws `undefined name error` for annotated variables in functions

### ISSUE THREAD

**Issue by jensgustafsson** [PyCQA/pyflakes#373]
I have a Python code base that is built with Python3.4 (which doesn't have type annotations) but it has annotations. In prior versions of pyflakes 2.0.0 the example file below was "considered ok" by `pyflakes`.

*Example file:* `test.py`:
```
def annotated_f(a: 'annotated'):
    print(a)
```

When I run `pyflakes test.py` I get `test.py:4: undefined name 'annotated'`. Should it not be possible to use `annotations` together with pyflakes anymore?

**Comment by AxelVoitier** [comment]
I run into similar issue as well (due to the recent update of flake8).

In my case, having a comment sentence in an annotation gives something like ```syntax error in forward annotation 'this is a comment'```.

For information, it is a valid way of using comments in annotations for such use cases where a third-party lib is using it for presenting it to the user. For instance, that's how you present a help text when invoking your program using [begins](https://pypi.org/project/begins/).

In the case of the syntax error I could trace it back to this commit: 8aece72839adb4add6c31ccfcb021cef2d731a81.
It wrongly assumes string literal annotations are all forward references annotations.
I guess the ```undefined name``` you reported is also coming implicitly from here.

String literal annotations are PEP 563 solution for forward reference in annotation. But that's only if you want to do type checking on them. PEP 3107 allows string literal annotations to be anything in absolute.

The worst is that you could have a mix of these. Likely in a same package or module/file. Less likely, but still valid, in the same function description...

**Comment by jensgustafsson** [comment]
The Flake8 update was the source of truble for us as well.

In our code we're using annotations to do dependency injections.

We have a decorator that injects kwargs for all variables that are annotated with `inject` in the function it's decorarting. It's not a pythonic solution at all since it's very implicit but it's used in many places and I don't want to rewrite that code right now. But since it's valid python I think it's weird that it's considered a linting error.

The only options I have right now is to globally ignore the error in the codebase which is built up by several packages or to freeze my dependencies. I don't like any of the solutions... A third option is to rewrite the codebase but that's not feasible atm.

**Comment by Artimi** [comment]
I stumbled upon this when trying error codes in mypy https://mypy.readthedocs.io/en/latest/error_codes.html#silencing-errors-based-on-error-codes. When I have a code like this:
```		
pkg_resources.SetuptoolsVersion, #type: ignore[attr-defined]
```
Pyflakes has the following output:
```
requirements.py:24: undefined name 'ignore'
requirements.py:24: undefined name 'attr'
requirements.py:24: undefined name 'defined'
```

**Comment by asottile** [comment]
@Artimi already fixed on master, see #475 #455

**Comment by Artimi** [comment]
@asottile Cool, thanks for directing me to the answer. :+1:

**Comment by Artimi** [comment]
@asottile When will be the new version of pyflakes released?

**Comment by asottile** [comment]
no idea :man_shrugging: -- the next release will be a minor release though as there are new features

**Comment by Artimi** [comment]
Ok, thanks for the info. It would help us very much if you could release something quickly what we could use because our build is failing. Is there some blocker?

**Comment by asottile** [comment]
tbh I wouldn't expect it soon, why is your build failing? can't you either use the old syntax or noqa until then? (seems like an extremely minor feature to rush a release over)

**Comment by asottile** [comment]
to the original issue, from [PEP 563](https://www.python.org/dev/peps/pep-0563/#rationale-and-goals):

> In Python 3.8 PEP 484 will graduate from provisional status. Other enhancements to the Python programming language like PEP 544, PEP 557, or PEP 560, are already being built on this basis as they depend on type annotations and the typing module as defined by PEP 484. In fact, the reason PEP 484 is staying provisional in Python 3.7 is to enable rapid evolution for another release cycle that some of the aforementioned enhancements require.
>
> With this in mind, uses for annotations incompatible with the aforementioned PEPs should be considered deprecated.

given the official stance that annotations incompatible with the typing peps are deprecated closing this as invalid -- thanks again for the issue!

**Comment by Artimi** [comment]
We use it for example for classes that we don't want to import only for the sake of typing:
```
class Controller:
  def __init__(self, application_container: 'lib.di.ApplicationContainer'):
    pass
```
As you can see we don't import the `lib.di`. Mypy is happy with this but `pyflakes` raises an error. This is failing our build. What would you recommend us?

Also, the fact that annotation prior annotations are deprecated for Python 3.8 (which is not released yet) does not mean that it is deprecated for lower versions. And as I can see in `pyflakes` `setup.py` you are supporting also older versions https://github.com/PyCQA/pyflakes/blob/master/setup.py#L57

**Comment by asottile** [comment]
you're mistaken:

```console
$ mypy t.py
t.py:2: error: Name 'lib' is not defined
Found 1 error in 1 file (checked 1 source file)
```

**Comment by asottile** [comment]
you can always use the `TYPE_CHECKING` trick:

```python
if TYPE_CHECKING:
    import lib

...
```

or if you need to support python3.5.0-3.5.2:

```python
if False:  # TYPE_CHECKING
    import lib

...
```

**Comment by Artimi** [comment]
You are right. I don't know why our mypy didn't warn us about that. We will fix it. Anyway, pyflakes is blocking us from using error codes because the fix in https://github.com/PyCQA/pyflakes/pull/455 is not released yet. We don't use unreleased version as this would bring a lot of dependency conflicts to our infrastructure. I would really appreciate if you could release the current master as a new version.
