### ISSUE TITLE
Ignore variables starting with underscore `_`

### ISSUE THREAD

**Issue by NickeZ** [PyCQA/pyflakes#393]
Many tools ignore unused variables starting with underscore. Typically you use this convention as a sort of "documentation" like so:

```
except ValueError as _err:
```

or
```
_head, tail = my_str.split(' ', 1)
```

Is this something you would consider implementing?

**Comment by krader1961** [comment]
That hasn't been my experience. A single leading underscore is most often meant to signal the var represents an implementation detail and is not part of the public interface. The only magic var that should be used in the manner you suggest is `_`. Most often to signal that a function parameter is explicitly ignored. See issue #202 where this was extensively discussed.

P.S., I would write your example as `tail = my_str.split(' ', 1)[1]`.

**Comment by NickeZ** [comment]
My 2 datapoints:

* pylint accepts it. See:
  * https://github.com/PyCQA/pylint/blob/master/pylint/test/functional/unused_variable.py#L11
  * https://github.com/PyCQA/pylint/blob/master/pylint/test/functional/unused_variable.txt
* in rust it is also common practice.
  * https://github.com/rust-lang/rust-clippy/blob/master/tests/ui/used_underscore_binding.stderr

**Comment by krader1961** [comment]
I consider the `pylint` behavior wrong. So much so that I put the following in my *~/.pylintrc*:

```
# A regular expression matching the name of dummy variables (i.e. expectedly
# not used).
dummy-variables-rgx=^unused_|_$|dummy
```

In code I work with I've never seen a case of `Unused variable '_foo'` from pylint where the code wasn't improved by removing the unused var or replacing it with just `_` to make it clear the value was being discarded. And the latter transformation doesn't lose any information IMHO. Your original example, for example, isn't any clearer for using `_head` versus `_` or the alternative using a slice I would have written.

The problem is that I have seen plenty of instances where a `_foo` style var name really did represent a problem. Usually because the var used to be used but then a change was introduced which made the var irrelevant but its definition wasn't removed.

**Comment by NickeZ** [comment]
OK one super-typical example is:

```
for _root, _dirs, files in os.walk():
```

I would never write it like below:

```
for _, _, files in os.walk():
```

I like the self-documenting behavior of actually naming the ignored variables. But I bet I can make flakes ignore unused variables with some configuration. Thanks for your time.

**Comment by asmeurer** [comment]
Pyflakes already ignores unused variables from unpackings and unused loop variables.

**Comment by NickeZ** [comment]
Ok, but not in catching exceptions.

**Comment by asmeurer** [comment]
You mean like if `e` is unused as in `except Exception as e`? Why write `as e` at all if you're not going to use it?

**Comment by NickeZ** [comment]
No that is not what i meant, see my first comment.

**Comment by sigmavirus24** [comment]
I don’t understand how binding the exception counts as documentation or why you’d want to bind it without using it. Your code, regardless of leading underscores is functionally equivalent to binding it to a non-underscore-prefixed name and if you’re not using it is in fact lint.

**Comment by NickeZ** [comment]
I agree, this case is kind of stupid since this is one of the few cases where you actually mention the type right before, so it is very obvious what the value contains. But I basically quit using only underscore for all other cases so by pure habit I write `_err` instead of `_` in this case. In this case I could even skip `as _` completely but I want to keep this `except` consistent with the other ones.

**Comment by g4borg** [comment]
This would really be helpful to be honest.

> I consider the pylint behavior wrong. So much so that I put the following in my ~/.pylintrc:
It is not. _ is used mostly as gettext, and not just in django land; its a google goism, that has been deprecated even at google, but the principle of using _variables has been around.
Since you can write a regexp to another modules behaviour, it would be easier to turn it off, than not supporting it.

starting an unused variable with underscore is very much used, and even editors come with support for it out of the box.

I have seen both usages since years and prefer some variable name after the "_". It only denotes privacy if it is a method or member, and even then, it is to be seen as "unused".

Finally, writing _err is much more readable and pythonic, than using _.

**Comment by bashirmindee** [comment]
I also think that this would be a great feature that flakes is missing and not implementing it is making developers lives harder. Rust follows this standard.
