### ISSUE TITLE
Linter false red flag on try-try-finally

### ISSUE THREAD

**Issue by OverLordGoldDragon** [PyCQA/pyflakes#518]
```python
def f():
    a = "a"
    try:
        print("`try` executed")
    except:    
        print("`except` executed")
        try:
            pass
        finally:
            print("`finally` executed")
            del a
    print(a)
f()
```
```
`try` executed
a
```

<img src="https://user-images.githubusercontent.com/16495490/75593452-d7cb9f00-5a9e-11ea-86ed-2f68432a3549.png" width="300">

<hr>

Something like "`a` may be undefined" may be more appropriate. The IDE's Spyder, [Issue](https://github.com/spyder-ide/spyder/issues/11683) ported per a dev's comment.

**Comment by asottile** [comment]
pyflakes does not do branch analysis, and this code could still trigger a UnboundLocalError (`print` for instance could raise `MemoryError`):
```
$ python3 t.py
`except` executed
`finally` executed
Traceback (most recent call last):
  File "t.py", line 13, in <module>
    f()
  File "t.py", line 12, in f
    print(a)
UnboundLocalError: local variable 'a' referenced before assignment
```

I believe pyflakes is correct to mark this code as suspicious (and it couldn't solve the halting problem to prove otherwise) -- thanks for the issue but this is working as intended
