### ISSUE TITLE
False positive: F821 when using references to types in functions

### ISSUE THREAD

**Issue by samuelcolvin** [PyCQA/pyflakes#529]
The following code causes an error `test.py:6:21: F821 undefined name 'Foobar'` with `pyflakes==2.2.0`, but passes with `pyflakes==2.1.1` and `mypy==0.770`.

```py
from typing import Optional

def my_function() -> None:
    class Foobar:
        x: Optional['Foobar']
```
I think this is should be considered valid.

Obviously it works fine if `Foobar` is defined outside a function.

Seems to be similar to #496, but that's marked as fixed.

---

There are also some more subtle cases used by pydantic, which fail with mypy, e.g.:

```py
def return_type(setting: str) -> Type[Any]:
    return str

class MyClass:
    foo: return_type('foobar')
```
which also gives `F821 undefined name 'foobar'`

I'm not sure if you:
1. think this is the same issue? (I can create another issue if you like)
2. think this is a bug?

**Comment by asottile** [comment]
the former I agree is a bug, the latter is incompatible with PEP 484 so I don't think it's a bug

**Comment by asottile** [comment]
A workaround (but probably not a solution for everyone) is to either:

(1) quote the entire anntations
(2) use `from __future__ import annotations`

which likely means we aren't properly deferring the quoted part of the annotation

**Comment by samuelcolvin** [comment]
Thanks, could you point to where in the PEP that's stated? Just for reference, as it's something we do a lot in pydantic.

Would also be useful to have a separate error code for this?

**Comment by asottile** [comment]
I'm mostly looking at the guidance from [this section](https://www.python.org/dev/peps/pep-0484/#acceptable-type-hints) -- I believe a future PEP should have a better solution for attaching arbitrary data via annotations which would directly support the features you're looking for:  [PEP 593](https://www.python.org/dev/peps/pep-0593/)

though pyflakes doesn't yet support `Annotated` (though there's special handling for `Literal` and it would probably work the same way!)

**Comment by asottile** [comment]
if someone wants to tackle this, here's the triage/hint:

https://github.com/PyCQA/pyflakes/blob/c72d6cf1a9a119c1dd7a7674f36da21aea32d828/pyflakes/checker.py#L1740-L1743

this `def STR` is called for string annotations and checks `self._in_deferred` (it is trying to know whether it's running a deferred check for annotations) and if it is it eagerly checks the string annotation

the problem is that there are multiple things that can be deferred: functions, annotations (and a check for unused assignments)

what would _probably_ fix this would be to split the deferred functions from the deferred annotations and have two separate state variables for the two.  run the deferred functions first, then run the deferred annotations, and adjust this check to only respond to the state variable for the annotations

**Comment by jack1142** [comment]
I'm not entirely sure if this is the same issue but it's also related to strings in function annotations.
This code:
```py
class TimedeltaConverter:
    def __init__(self, *, default_unit=None):
        self.default_unit = default_unit


def slowmode(interval: TimedeltaConverter(default_unit="seconds")):
    pass
```
Results in:
```
test.py:6:56: F821 undefined name 'seconds'
def slowmode(interval: TimedeltaConverter(default_unit="seconds")):
```

Version info:
```
λ flake8 --version
3.8.3 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.8.3 on Windows
```

**Comment by asottile** [comment]
not the same, that's not a valid PEP 484 type so pyflakes is correct to flag it:

```console
$ mypy t.py
t.py:6: error: Invalid type comment or annotation
t.py:6: note: Suggestion: use TimedeltaConverter[...] instead of TimedeltaConverter(...)
Found 1 error in 1 file (checked 1 source file)
```

**Comment by jack1142** [comment]
From the PEP 484:
```
Note that this PEP still explicitly does NOT prevent other uses of annotations, nor does it require (or forbid) any particular processing of annotations, even when they conform to this specification. It simply enables better coordination, as PEP 333 did for web frameworks.
```

pyflakes is not a type checker as far as I can tell, so I don't think it should error when you put in function annotation something that is not valid according to PEP 484.

**Comment by samuelcolvin** [comment]
I would agree with @jack1142 this should not be an error, or at the very least it should be under a special error code so such errors can easily be ignored.

**Comment by sigmavirus24** [comment]
PEP 484 gives meaning to the annotations though and allows pyflakes to provide more insight and better linting when conforming more to that than the ambiguous original "they can be anything, anything at all" definition.

> it should be under a special error code so such errors can easily be ignored.

Pyflakes itself doesn't allow you to ignore errors nor does it generate its own error codes. As for the specific case in https://github.com/PyCQA/pyflakes/issues/529#issuecomment-645697844, it sounds like you're advocating that we try to invent some new error during the course of processing type hints to indicate that something was referenced without previously being defined. Is that accurate?

**Comment by jack1142** [comment]
Well, this is an invalid **type** annotation, so I think it would make sense to separate errors that are related to incorrectness of type annotation, instead of showing F821 error for something that is not actually related to the undefined name.

I find undefined name errors incredibly useful so I wouldn't want to disable F821 error, but I also don't want to run into false positives as in this case where the mentioned "seconds" is actually a literal in function call, not a reference of a type like it would be in `Optional["SomeType"]` case.

**Comment by asottile** [comment]
let's continue the discussion in #594 for implementing `Annotated`
