### ISSUE TITLE
Is an unused variable annotation able to be detected?

### ISSUE THREAD

**Issue by scottbelden** [PyCQA/pyflakes#546]
Given this sample file:

```python
def foo():
    a = 10
    b: str
    return 1


foo()
```

It correctly gives an error about the variable `a`: `test.py:2:5 local variable 'a' is assigned to but never used`

It would be nice if an error could be given about `b` as well since it is also never used. I'm not sure if this is a bug report or a feature request, but I just wasn't sure if this was possible.

**Comment by asottile** [comment]
yep this is possible -- this would _probably_ be a feature (and a separate code) since it's a little different than our name binding right now

it is possible to detect this case, and I believe the work done in #535 will make this very easy to implement!

there's even a TODO mentioning your expected behaviour: https://github.com/PyCQA/pyflakes/pull/535/files#diff-8dd6768783dc8a438172318bc691ac3eR294

if you'd like to help move it forward, I'd suggest trying out that branch and if you're up for it reviewing the code
