### ISSUE TITLE
Missing pips

### ISSUE THREAD

**Issue by nomasprime** [PyCQA/pyflakes#556]
Hi, fairly new to Python, trying to find my way around.

When I had pylint installed it was warning me about missing pips. From quick research it looks like flake8 is more popular these days but I noticed it doesn't warn me of missing pips like pylint does. Is this something pyflakes can do?

**Comment by asottile** [comment]
what do you mean by missing pips? like missing dependencies?  no pyflakes can't / shouldn't do that it is a static analysis tool not a dynamic one

**Comment by nomasprime** [comment]
@asottile yep. [Article](https://blog.codacy.com/which-python-static-analysis-tools-should-i-use/) I read compared the two but speed read so maybe missed something. Presumably this would come with a considerable performance hit anyway.

Any comparisons between flake8/pyflakes and pylint would be helpful.

**Comment by nomasprime** [comment]
Insightful 😄 No problem, I'll figure it out.

**Comment by sigmavirus24** [comment]
@nomasprime No pyflakes won't inspect your site-packages to determine if you've not installed something. That's why it's faster. There are extensions to Flake8 that will do that though. Flake8, however, uses itself and pylint for linting. Both tools are useful and have some overlap but have far more things that the other does well. It's not our job to explain that to you in this issue.
