### ISSUE TITLE
w605 error

### ISSUE THREAD

**Issue by GianniGi** [PyCQA/pyflakes#579]
*Please describe how you installed Flake8*

$ pip install --user flake8

*Please describe the problem or feature*

I'm using flake8 with coc.nvim inside vim8.2

flake8 shows the w605 error for indentation problems inside comments. The comment can be made with ''' or with #, it shows the error in any casel.

*How to reproduce the problem*

save a file with extension .py and with this comment

```
print()



'''
classe \s
<r>[\s]</r>
# 1 condizione\.
# 1 condizione.{1,1}\.

'''
```

**Comment by asottile** [comment]
pyflakes doesn't have W* error codes, you're looking for pycodestyle

but either way your issue is invalid, you want a raw string (prefixed with a r). if you're confused, search around for your error code

**Comment by GianniGi** [comment]
why can't I write what I want in my comments?

Il giorno lun 21 set 2020 alle ore 00:14 Anthony Sottile <
notifications@github.com> ha scritto:

**Comment by asottile** [comment]
because in future python versions it will be a syntax error, you can enable the warning ahead of time yourself if you'd like:

```console
$ python3.8 -Werror t.py
  File "t.py", line 5
    '''
    ^
SyntaxError: invalid escape sequence \s
```

If you'd searched you would have found all of these issues telling you the same thing:
- https://github.com/PyCQA/pycodestyle/issues/958
- https://github.com/PyCQA/pycodestyle/issues/949
- https://github.com/PyCQA/pycodestyle/issues/902
- https://github.com/PyCQA/pycodestyle/issues/854
- https://github.com/PyCQA/pycodestyle/issues/822
- https://github.com/PyCQA/pycodestyle/issues/814
- https://github.com/PyCQA/pycodestyle/issues/766
- https://gitlab.com/pycqa/flake8/-/issues/474
- https://gitlab.com/pycqa/flake8/-/issues/465

and this was just from putting W605 into the search box, there's plenty more that can explain your problem.  please do some research as I've asked you to several times now

**Comment by GianniGi** [comment]
The point is that comments are comments. I write all sort of gibberish in
them and I don't need any plugin to check what I wrote. This is the point.
Not the w666.

Il giorno lunedì 21 settembre 2020, Anthony Sottile <
notifications@github.com> ha scritto:

**Comment by asottile** [comment]
that's not a comment, that's a string

**Comment by GianniGi** [comment]
You're crazy. It happens the same also with #

Il lun 21 set 2020, 00:59 Anthony Sottile <notifications@github.com> ha
scritto:

**Comment by asottile** [comment]
```console
$ cat t.py 
# \n\o \i\t \d\o\e\s\n\'\t
$ flake8 t.py 
$
```

**Comment by sigmavirus24** [comment]
@GianniGi calling people crazy is wildly inappropriate. I've locked this because you've not put the effort into finding the appropriate issue tracker and you're being offensive. 

You mentioned elsewhere you were using Flake8, you can disable `W605` and there are  docs for that. Please read those.
