### ISSUE TITLE
Changed behavior for global variables with explicit type annotation

### ISSUE THREAD

**Issue by parhamfh** [PyCQA/pyflakes#621]
When upgrading to pyflakes 2.3.0 (through [flake8 3.9.0](https://gitlab.com/pycqa/flake8/-/blob/434c108f7491b589362752b12979741598bb2dff/docs/source/release-notes/3.9.0.rst)) a warning is given for code that previously passed. I am however unsure if the code is incorrect/undefined somehow or if this should be accepted by pyflakes. 

It is regarding a global variable declaration without value but with explicit type annotation. The variable is assigned a value in a module-level function and the warning is given for other module-level functions which reference the global variable. 

Here is a minimal reproducible example which gives the following warning in latest version: `global.py:14:11 undefined name 'my_dict'`

```python
from typing import Dict

my_dict: Dict[str, str]

def a():
    global my_dict
    my_dict = {}
    print("A")

def run():
    print(my_dict)

if __name__ == "__main__":
    a()
    run()
```

In pyflakes 2.2.0 there is no warning, and the code runs fine. However, if `a()` is not executed before `run()` the code would obviously produce this error:

```python
Traceback (most recent call last):
  File "global.py", line 19, in <module>
    run()
  File "global.py", line 14, in run
    print(my_dict)
NameError: name 'my_dict' is not defined
```

**Comment by asottile** [comment]
error seems correct to me, as you state:

>  if a() is not executed before run() the code would obviously produce this error

you can give the global an initial value to avoid the error

**Comment by henzef** [comment]
Could you please reconsider closing this as wontfix? In some cases an initial value doesn't make any sense and/or would require constructing a complex object. Alternatively one might set the default to None, but that would require the Optional[] annotation, which might not make sense semantically ...
Also there is no easy way to accept this via a noqa comment, because the F821 warning is reported on *every* line accessing the global variable as opposed to once when the type is annotated.

**Comment by asottile** [comment]
ping-ponging through global variables I believe is something pyflakes *should* report as an error (it's a programming error waiting to happen).

If you're using flake8 you can utilize `per-file-ignores` for F821 on the file in question (though you're potentially turning off _all_ NameError detection)

another pattern which may be better than relying on side-effects reassigning variables:

```python
@functools.lru_cache(maxsize=1)
def get_complex_global() -> WhateverType:
    ...
```

**Comment by henzef** [comment]
Turning off all F821 would something I would like to avoid. In my case it's a module with the following structure:

one: MyType
two: OtherType
evenmore: ...  # really many more ;-)

def _local_fun():
    pass  # uses several global vars

def _local_fun2(may, have, args, or_, not_):
    pass # uses several global vars

def only_public_function_in_this_module(onearg, twoarg, evenmoreargs):
    global one, two, evenmore
    one = onearg
    two = twoarg
    evenmoreargs = evenmore
    
    # use all the local helper functions
    _local_fun()
    _local_fun2(...)
    
    return whatever_was_calculated

As you can see a programming error is unlikely with only a single public function. also the cached getter would not work, because the variables are passed as arguments.

**Comment by asottile** [comment]
yeah this seems like poorly designed code -- I'd recommend refactoring to passing arguments to functions instead of pingponging through global variables

**Comment by henzef** [comment]
I disagree. The code in its previous state was unreadable.

**Comment by Sh3Rm4n** [comment]
Besides the discussion, if this code is actually good style or not, `undefined name` is not really a descriptive error in this case and is wrong in this context, when taking the error description (https://www.flake8rules.com/rules/F821.html) into consideration. 

Would it technically be possible to special case this incidence, maybe introducing a new error code, so that it can be ignored, if desired?

**Comment by sigmavirus24** [comment]
There's no good reason to special case this. Pyflakes can be fairly certain that your code will break (even if right now it's not) and it's warning you about that. This has turned into a "the tool may be detecting a real problem but I don't care because of my opinions on code style" discussion and isn't productive any longer. I'm locking the issue.
